// frontend/src/features/returns/pages/ReturnDetailPage.tsx
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../../../api/client';
import type { ReturnDetail } from '../../../types';
import { ReturnStatusBadge } from '../components/ReturnStatusBadge';

export function ReturnDetailPage() {
  const { returnId } = useParams();
  const [detail, setDetail] = useState<ReturnDetail | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!returnId) return;
    api.getReturn(returnId).then(setDetail).catch((caught) => setError(String(caught)));
  }, [returnId]);

  if (!returnId) return <div className="rounded-3xl border border-slate-200 bg-white p-5 text-sm text-slate-600">Missing return id.</div>;
  if (error) return <div className="rounded-3xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</div>;
  if (!detail) return <div className="rounded-3xl border border-slate-200 bg-white p-5 text-sm text-slate-600">Loading return detail...</div>;

  return (
    <div className="space-y-4">
      <div className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <div className="text-xs uppercase tracking-[0.24em] text-slate-500">Return Detail</div>
            <h1 className="mt-2 text-2xl font-semibold text-slate-950">{detail.external_return_id ?? detail.id}</h1>
            <div className="mt-2 text-sm text-slate-600">Created by {detail.created_by ?? 'system'} on {new Date(detail.created_at).toLocaleString()}</div>
          </div>
          <div className="space-y-2 text-right">
            <ReturnStatusBadge status={detail.return_status} />
            <div className="text-sm text-slate-600">Fraud score {detail.fraud_risk_score != null ? Number(detail.fraud_risk_score).toFixed(1) : '—'}</div>
            <div className="text-sm text-slate-600">Decision {detail.fraud_decision ?? 'Pending'}</div>
          </div>
        </div>
      </div>

      <div className="grid gap-4 xl:grid-cols-[1.05fr_0.95fr]">
        <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm">
          <div className="text-xs uppercase tracking-[0.24em] text-slate-500">Order</div>
          <div className="mt-2 text-lg font-semibold text-slate-900">{String(detail.order.product_name ?? detail.order.external_order_id ?? detail.order_id)}</div>
          <div className="mt-3 grid gap-3 md:grid-cols-2">
            <Summary label="Reason category" value={detail.return_reason_category ?? '—'} />
            <Summary label="Condition" value={detail.condition_reported ?? '—'} />
            <Summary label="Return method" value={detail.return_method ?? '—'} />
            <Summary label="Refund method" value={detail.preferred_refund_method ?? '—'} />
            <Summary label="Refund amount" value={detail.refund_amount != null ? `$${Number(detail.refund_amount).toFixed(2)}` : '—'} />
            <Summary label="Hours after delivery" value={detail.hours_after_delivery != null ? Number(detail.hours_after_delivery).toFixed(1) : '—'} />
          </div>
          <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700">
            <div className="text-xs uppercase tracking-[0.22em] text-slate-500">Detailed description</div>
            <div className="mt-2 leading-6">{detail.detailed_description ?? detail.return_reason ?? '—'}</div>
          </div>
        </section>

        <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm">
          <div className="text-xs uppercase tracking-[0.24em] text-slate-500">Supporting Evidence</div>
          <div className="mt-2 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-600">Image upload will be available in the next release.</div>
          <div className="mt-4 text-xs uppercase tracking-[0.24em] text-slate-500">Timeline</div>
          <div className="mt-3 space-y-2">
            {detail.timeline.map((event) => (
              <div key={`${event.label}-${event.time}`} className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3">
                <div className="text-sm font-medium text-slate-900">{event.label}</div>
                <div className="mt-1 text-xs text-slate-500">{new Date(event.time).toLocaleString()}</div>
              </div>
            ))}
          </div>
          <div className="mt-4 flex gap-2">
            <Link to={`/orders/${detail.order_id}?tab=returns`} className="rounded-2xl bg-slate-950 px-4 py-2 text-sm font-medium text-white">Back to order</Link>
            <Link to={`/orders/${detail.order_id}/returns/create`} className="rounded-2xl border border-slate-200 bg-white px-4 py-2 text-sm text-slate-700">Create another return</Link>
          </div>
        </section>
      </div>

      <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm">
        <div className="text-xs uppercase tracking-[0.24em] text-slate-500">Return Items</div>
        <div className="mt-3 overflow-hidden rounded-3xl border border-slate-200">
          <table className="min-w-full text-left text-sm">
            <thead className="bg-slate-50 text-slate-500">
              <tr>
                <th className="px-4 py-3">Product</th>
                <th className="px-4 py-3">Qty</th>
                <th className="px-4 py-3">Condition</th>
                <th className="px-4 py-3">Status</th>
              </tr>
            </thead>
            <tbody>
              {(detail.items ?? []).map((item) => (
                <tr key={item.id} className="border-t border-slate-100 bg-white">
                  <td className="px-4 py-3">
                    <div className="font-medium text-slate-900">{item.product_name ?? 'Product'}</div>
                    <div className="text-xs text-slate-500">SKU {item.sku ?? '—'}</div>
                  </td>
                  <td className="px-4 py-3 text-slate-700">{item.quantity}</td>
                  <td className="px-4 py-3 text-slate-700">{item.declared_condition ?? '—'}</td>
                  <td className="px-4 py-3 text-slate-700">{item.item_match_status ?? '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}

function Summary({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
      <div className="text-[11px] uppercase tracking-[0.22em] text-slate-500">{label}</div>
      <div className="mt-2 text-sm font-medium text-slate-900">{value}</div>
    </div>
  );
}

// shop/src/pages/ReturnDetailPage.vue
<script setup>
import { ref, onMounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import { api } from '../api/client'
import { ArrowLeft, Shield, Loader, CheckCircle, AlertTriangle, Image as ImageIcon } from '../components/icons.js'

const props = defineProps({ returnId: { type: String, required: true } })
const router = useRouter()

const detail = ref(null)
const loading = ref(true)
const error = ref('')

onMounted(async () => {
  try {
    detail.value = await api.getReturnDetail(props.returnId)
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
})

const riskTone = computed(() => {
  const d = detail.value?.fraud_decision
  if (d === 'HOLD_REFUND_HIGH_RISK') return 'rose'
  if (d === 'MANUAL_REVIEW') return 'amber'
  return 'emerald'
})
</script>

<template>
  <button @click="router.push('/orders')" class="btn-ghost mb-4 text-xs">
    <ArrowLeft class="h-4 w-4" /> Back to orders
  </button>

  <div v-if="loading" class="grid place-items-center py-20 text-slate-400">
    <Loader class="h-6 w-6 animate-spin" />
  </div>

  <div v-else-if="error" class="card border-rose-200 bg-rose-50 p-5 text-sm text-rose-700">
    <AlertTriangle class="mb-1 h-4 w-4" /> {{ error }}
  </div>

  <div v-else-if="detail" class="space-y-5">
    <!-- Decision banner -->
    <div class="card overflow-hidden p-0">
      <div class="px-5 py-5" :class="{
        'bg-emerald-50': riskTone === 'emerald',
        'bg-amber-50': riskTone === 'amber',
        'bg-rose-50': riskTone === 'rose',
      }">
        <div class="flex items-center gap-3">
          <div class="grid h-11 w-11 place-items-center rounded-xl bg-white shadow-sm" :class="{
            'text-emerald-600': riskTone === 'emerald',
            'text-amber-600': riskTone === 'amber',
            'text-rose-600': riskTone === 'rose',
          }">
            <Shield class="h-5 w-5" />
          </div>
          <div>
            <div class="text-xs font-medium uppercase tracking-wide text-slate-500">Return decision</div>
            <div class="text-lg font-bold text-slate-900">{{ detail.fraud_decision || detail.fraud_screening_status || 'PENDING' }}</div>
          </div>
          <div v-if="detail.fraud_risk_score != null" class="ml-auto text-right">
            <div class="text-2xl font-extrabold">{{ detail.fraud_risk_score.toFixed(1) }}</div>
            <div class="text-[11px] text-slate-500">fraud risk</div>
          </div>
        </div>
      </div>
      <div class="grid gap-3 px-5 py-4 text-sm sm:grid-cols-3">
        <div><dt class="text-slate-400">Return ID</dt><dd class="font-mono">{{ detail.external_return_id }}</dd></div>
        <div><dt class="text-slate-400">Status</dt><dd class="font-medium">{{ detail.return_status }}</dd></div>
        <div><dt class="text-slate-400">Screening</dt><dd class="font-medium">{{ detail.fraud_screening_status }}</dd></div>
      </div>
    </div>

    <div class="grid gap-5 lg:grid-cols-2">
      <div class="card p-5">
        <h2 class="text-sm font-semibold uppercase tracking-wide text-slate-500">Return details</h2>
        <dl class="mt-3 space-y-2 text-sm">
          <div class="flex justify-between"><dt class="text-slate-500">Reason</dt><dd class="font-medium text-right">{{ detail.return_reason_category }}</dd></div>
          <div class="flex justify-between"><dt class="text-slate-500">Condition</dt><dd class="font-medium capitalize">{{ detail.condition_reported }}</dd></div>
          <div class="flex justify-between"><dt class="text-slate-500">Method</dt><dd class="font-medium">{{ detail.return_method }}</dd></div>
          <div class="flex justify-between"><dt class="text-slate-500">Refund to</dt><dd class="font-medium">{{ detail.preferred_refund_method }}</dd></div>
          <div v-if="detail.refund_amount != null" class="flex justify-between"><dt class="text-slate-500">Refund amount</dt><dd class="font-bold text-emerald-600">${{ detail.refund_amount.toFixed(2) }}</dd></div>
        </dl>
        <p v-if="detail.detailed_description" class="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{{ detail.detailed_description }}</p>
      </div>

      <div class="card p-5">
        <h2 class="text-sm font-semibold uppercase tracking-wide text-slate-500">Items returned</h2>
        <ul class="mt-3 space-y-2">
          <li v-for="i in detail.items" :key="i.id" class="flex items-center justify-between rounded-xl border border-slate-100 px-3 py-2 text-sm">
            <div>
              <div class="font-medium">{{ i.product_name }}</div>
              <div class="text-xs text-slate-500">SKU {{ i.sku }} · {{ i.item_match_status }}</div>
            </div>
            <span class="badge bg-slate-100 text-slate-600">Qty {{ i.quantity }}</span>
          </li>
        </ul>
      </div>
    </div>

    <div class="card p-5">
      <h2 class="flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-slate-500">
        <ImageIcon class="h-4 w-4" /> Image verification
      </h2>
      <p v-if="!detail.timeline?.some((t) => t.label.includes('Image'))" class="mt-2 text-sm text-slate-500">No image was attached to this return.</p>
      <ul v-else class="mt-3 space-y-2 text-sm">
        <li v-for="t in detail.timeline" :key="t.label + t.time" class="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2">
          <span class="flex items-center gap-2">
            <CheckCircle v-if="t.label.includes('Completed')" class="h-4 w-4 text-emerald-500" />
            <AlertTriangle v-else-if="t.label.includes('Mismatch') || t.label.includes('Failed')" class="h-4 w-4 text-amber-500" />
            <Shield v-else class="h-4 w-4 text-slate-400" />
            {{ t.label }}
          </span>
          <span class="text-xs text-slate-400">{{ new Date(t.time).toLocaleString() }}</span>
        </li>
      </ul>
    </div>
  </div>
</template>
